const DEFAULT_PRODUCTS=[
{id:"classic",name:"Classic Tea",category:"Black Tea",price:299,size:"250 g",desc:"A balanced everyday tea with a warm aroma and familiar character."},
{id:"premium",name:"Premium Tea",category:"Black Tea",price:399,size:"250 g",desc:"A richer cup designed around aroma, depth and a smooth finish."},
{id:"green",name:"Green Tea",category:"Green Tea",price:349,size:"100 g",desc:"A clean, delicate tea for a lighter everyday ritual."},
{id:"hibiscus",name:"Hibiscus Tea",category:"Herbal Tea",price:329,size:"100 g",desc:"A vibrant floral infusion with a refreshing character."},
{id:"butterfly",name:"Butterfly Pea Tea",category:"Specialty Tea",price:379,size:"100 g",desc:"A distinctive blue herbal infusion with an elegant presentation."},
{id:"chamomile",name:"Chamomile Tea",category:"Herbal Tea",price:359,size:"100 g",desc:"A gentle floral infusion made for slow, quiet moments."}
];
const getProducts=()=>JSON.parse(localStorage.getItem("sk_products")||"null")||DEFAULT_PRODUCTS;
const saveProducts=p=>localStorage.setItem("sk_products",JSON.stringify(p));
const cart=()=>JSON.parse(localStorage.getItem("sk_cart")||"[]");
const saveCart=c=>{localStorage.setItem("sk_cart",JSON.stringify(c));updateCartCount()};
function updateCartCount(){const n=cart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll("#cartCount").forEach(e=>e.textContent=n)}
function productPack(name){return `<div class="product-pack"><small>SURAJ KIRAN</small><strong>${name}</strong><small>TEA</small></div>`}
function card(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-media">${p.image?`<img src="${p.image}" alt="${p.name}">`:productPack(p.name)}<button class="quick-add" data-add="${p.id}" aria-label="Add ${p.name}">+</button></div></a><div class="product-body"><span class="product-cat">${p.category}</span><h3 class="product-name">${p.name}</h3><p class="product-desc">${p.desc}</p><div class="product-meta"><strong class="price">₹${Number(p.price).toLocaleString("en-IN")}</strong><a class="text-link" href="product.html?id=${p.id}">View details</a></div></div></article>`}
function bindAdds(){document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();addToCart(b.dataset.add)}))}
function addToCart(id){const c=cart(), item=c.find(x=>x.id===id);if(item)item.qty++;else c.push({id,qty:1});saveCart(c);alert("Added to your bag.");}
function renderProducts(){const grid=document.getElementById("productGrid"), feat=document.getElementById("featuredProducts");const products=getProducts();if(grid){const filters=[...new Set(["All",...products.map(p=>p.category)])];const box=document.getElementById("filters");let active="All";const draw=()=>{const q=(document.getElementById("searchInput").value||"").toLowerCase();grid.innerHTML=products.filter(p=>(active==="All"||p.category===active)&&(p.name+p.desc).toLowerCase().includes(q)).map(card).join("");bindAdds()};box.innerHTML=filters.map(x=>`<button class="filter ${x==="All"?"active":""}">${x}</button>`).join("");box.querySelectorAll(".filter").forEach(btn=>btn.onclick=()=>{active=btn.textContent;box.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");draw()});document.getElementById("searchInput").oninput=draw;draw()}if(feat){feat.innerHTML=products.slice(0,3).map(card).join("");bindAdds()}}
function renderDetail(){const el=document.getElementById("productDetail");if(!el)return;const id=new URLSearchParams(location.search).get("id")||"premium",p=getProducts().find(x=>x.id===id)||getProducts()[0];el.innerHTML=`<div class="detail-grid"><div class="detail-image">${p.image?`<img src="${p.image}" alt="${p.name}" style="width:100%;height:100%;object-fit:cover">`:productPack(p.name)}</div><div class="detail-copy"><span class="eyebrow">${p.category}</span><h1>${p.name}</h1><p>${p.desc}</p><strong class="price">₹${Number(p.price).toLocaleString("en-IN")}</strong><p class="muted">${p.size||"Pack size to be updated"}</p><div class="quantity"><button id="minus">−</button><input id="qty" type="number" min="1" value="1"><button id="plus">+</button></div><button class="btn btn-primary full" id="detailAdd">Add to Cart</button><div style="margin-top:30px"><h3>Product information</h3><p class="muted">Ingredients, storage instructions and final pack information can be added here before launch.</p></div></div></div>`;let q=document.getElementById("qty");document.getElementById("minus").onclick=()=>q.value=Math.max(1,+q.value-1);document.getElementById("plus").onclick=()=>q.value=+q.value+1;document.getElementById("detailAdd").onclick=()=>{const c=cart(),item=c.find(x=>x.id===p.id);if(item)item.qty+=+q.value;else c.push({id:p.id,qty:+q.value});saveCart(c);alert("Added to your bag.")}}
function renderCart(){const box=document.getElementById("cartItems");if(!box)return;const products=getProducts(),c=cart();if(!c.length){box.innerHTML='<div class="panel" style="background:#fff;padding:40px"><h2>Your bag is empty.</h2><a class="text-link" href="products.html">Explore our teas →</a></div>';document.getElementById("subtotal").textContent="₹0";document.getElementById("total").textContent="₹0";return}let total=0;box.innerHTML=c.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return"";total+=p.price*i.qty;return `<div class="cart-item"><div class="thumb">${p.image?`<img src="${p.image}" alt="" style="width:100%;height:100%;object-fit:cover">`:productPack(p.name)}</div><div><strong class="product-name" style="font-size:20px">${p.name}</strong><p class="muted small">${p.size}</p><div class="quantity" style="margin:8px 0"><button data-dec="${p.id}">−</button><span>${i.qty}</span><button data-inc="${p.id}">+</button></div></div><div class="cart-price"><strong class="price">₹${(p.price*i.qty).toLocaleString("en-IN")}</strong><button class="text-link" data-remove="${p.id}" style="border:0;background:none;margin-top:8px">Remove</button></div></div>`}).join("");document.getElementById("subtotal").textContent="₹"+total.toLocaleString("en-IN");document.getElementById("total").textContent="₹"+total.toLocaleString("en-IN");box.querySelectorAll("[data-inc]").forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));box.querySelectorAll("[data-dec]").forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));box.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{saveCart(cart().filter(x=>x.id!==b.dataset.remove));renderCart()});document.getElementById("checkoutBtn").onclick=()=>alert("Checkout is ready for payment integration in the next phase.")}
function changeQty(id,d){const c=cart(),i=c.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)saveCart(c.filter(x=>x!==i));else saveCart(c);renderCart()}
function admin(){if(!document.getElementById("adminProducts"))return;const list=document.getElementById("adminProducts"),form=document.getElementById("productForm");const render=()=>{list.innerHTML=getProducts().map(p=>`<div class="admin-row"><div class="admin-row-info"><div class="mini">${p.image?`<img src="${p.image}" style="width:100%;height:100%;object-fit:cover">`:"🍵"}</div><div><strong>${p.name}</strong><div class="muted small">${p.category} · ₹${p.price}</div></div></div><div class="admin-actions"><button data-edit="${p.id}">Edit</button><button data-del="${p.id}">Delete</button></div></div>`).join("");list.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{const p=getProducts().find(x=>x.id===b.dataset.edit);["id","name","category","price","size","desc","image"].forEach(k=>{const map={id:"pId",name:"pName",category:"pCategory",price:"pPrice",size:"pSize",desc:"pDesc",image:"pImage"};document.getElementById(map[k]).value=p[k]||""});location.hash="editor"});list.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("Delete this product?")){saveProducts(getProducts().filter(x=>x.id!==b.dataset.del));render()}})};form.onsubmit=e=>{e.preventDefault();const p={id:document.getElementById("pId").value||crypto.randomUUID(),name:document.getElementById("pName").value,category:document.getElementById("pCategory").value,price:+document.getElementById("pPrice").value,size:document.getElementById("pSize").value,desc:document.getElementById("pDesc").value,image:document.getElementById("pImage").value};const all=getProducts();const idx=all.findIndex(x=>x.id===p.id);if(idx>=0)all[idx]=p;else all.push(p);saveProducts(all);form.reset();document.getElementById("pId").value="";render();alert("Saved in this browser.")};document.getElementById("newProduct").onclick=()=>{form.reset();document.getElementById("pId").value=""};document.getElementById("resetForm").onclick=()=>form.reset();render()}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();renderProducts();renderDetail();renderCart();admin();const menu=document.getElementById("menuBtn"),nav=document.getElementById("mainNav");if(menu&&nav)menu.onclick=()=>nav.classList.toggle("open")});
